[2022-09-14 08:49:52,318] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 08:50:07,607] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 08:50:08,829] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 10:17:28,255] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 10:17:29,637] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 10:17:43,893] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 10:17:54,238] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 10:18:38,471] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 10:18:38,472] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9499
[2022-09-14 10:18:39,069] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 10:18:39,069] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9499
[2022-09-14 10:18:39,410] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist HTTP/1.1" 301 0
[2022-09-14 10:18:39,792] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37364
[2022-09-14 10:18:39,833] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:18:39,955] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:23:55,554] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37461
[2022-09-14 10:23:55,598] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:23:55,638] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:23:56,768] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 639
[2022-09-14 10:23:56,815] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:24:02,887] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 639
[2022-09-14 10:24:02,924] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:27:15,035] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 639
[2022-09-14 10:27:15,070] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:29:55,661] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 10:29:55,662] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9499
[2022-09-14 10:30:52,546] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 770
[2022-09-14 10:30:52,583] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:30:52,615] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:30:58,201] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addpark/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 128, in add_park
    wd = load_workbook(file_obj)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 315, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 78, in _validate_archive
    file_format = os.path.splitext(filename)[-1].lower()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2022-09-14 10:30:58,205] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addpark/ HTTP/1.1" 500 87973
[2022-09-14 10:31:00,978] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11287
[2022-09-14 10:31:01,010] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:31:05,792] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addpark/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 128, in add_park
    wd = load_workbook(file_obj)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 315, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\openpyxl\reader\excel.py", line 78, in _validate_archive
    file_format = os.path.splitext(filename)[-1].lower()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 204, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2022-09-14 10:31:05,795] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addpark/ HTTP/1.1" 500 87975
[2022-09-14 10:31:33,403] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 703
[2022-09-14 10:31:33,444] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:31:34,360] [log.py:224] [log:log_response] [WARNING]- Not Found: /park/
[2022-09-14 10:31:34,361] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /park/ HTTP/1.1" 404 9481
[2022-09-14 10:32:58,735] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 707
[2022-09-14 10:32:58,775] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 10:33:00,280] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37461
[2022-09-14 10:33:00,313] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:25:30,589] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 11:25:30,590] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9499
[2022-09-14 11:46:10,972] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37674
[2022-09-14 11:46:11,014] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:47:14,360] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37684
[2022-09-14 11:47:14,403] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:47:14,446] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:47:57,814] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11500
[2022-09-14 11:47:57,848] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:47:57,890] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:48:45,387] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11520
[2022-09-14 11:48:45,420] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:48:45,468] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:49:54,530] [log.py:224] [log:log_response] [WARNING]- Not Found: /parkedit/1/
[2022-09-14 11:49:54,531] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /parkedit/1/ HTTP/1.1" 404 9499
[2022-09-14 11:49:57,800] [log.py:224] [log:log_response] [WARNING]- Not Found: /parkedit/4/
[2022-09-14 11:49:57,801] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /parkedit/4/ HTTP/1.1" 404 9499
[2022-09-14 11:59:54,185] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37702
[2022-09-14 11:59:54,219] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 11:59:54,265] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 12:53:50,926] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 12:53:50,928] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9499
[2022-09-14 13:08:48,489] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:08:49,717] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:08:59,331] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:09:00,545] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:09:04,361] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:09:05,527] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:09:28,676] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:09:29,831] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:10:26,613] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:10:27,845] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:10:33,695] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:10:34,819] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:10:37,227] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:10:38,257] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:15,017] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:11:16,228] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:20,911] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:11:22,024] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:36,001] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:11:37,217] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:40,804] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:11:41,797] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:47,198] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:11:48,493] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:50,701] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:11:51,684] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:11:59,264] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:12:00,439] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:13:48,453] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:13:49,594] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:14:13,907] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:14:15,152] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:14:17,591] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:14:18,600] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:14:22,961] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:14:24,144] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:14:40,436] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:14:41,619] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:14:48,647] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:14:49,844] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:15:26,899] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 13:15:28,229] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:17:42,194] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 13:18:05,159] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:05,159] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:05,752] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:05,753] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:06,354] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:06,354] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:06,969] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:06,969] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:07,569] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:07,570] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:08,188] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:08,189] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:08,803] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:08,803] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:09,405] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:09,406] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:10,022] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:18:10,023] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9655
[2022-09-14 13:18:10,611] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101956
[2022-09-14 13:18:10,714] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:39:06,528] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:07,724] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:39:19,269] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:20,429] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:39:25,020] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:26,109] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:39:29,493] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:30,484] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:39:34,656] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:35,765] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:39:41,470] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:39:42,609] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:04,408] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:05,561] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:13,589] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:14,712] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:28,486] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:29,606] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:33,010] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:34,044] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:38,191] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:39,292] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:44,945] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:46,043] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:40:57,683] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:40:58,816] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:41:04,526] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:41:05,606] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:44:36,987] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:44:38,838] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 13:45:03,846] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:04,986] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:08,364] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:09,353] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:12,468] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:13,517] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:23,320] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:24,416] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:28,892] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:29,977] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:37,964] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:39,087] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:48,183] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:49,338] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:45:54,039] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:45:55,238] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:46:06,213] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:46:06,214] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9968
[2022-09-14 13:46:06,800] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:46:06,801] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9968
[2022-09-14 13:46:07,417] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:46:07,418] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 9968
[2022-09-14 13:46:08,179] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101965
[2022-09-14 13:46:08,378] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:46:08,587] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:46:09,837] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 724
[2022-09-14 13:46:09,894] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:46:12,479] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11439
[2022-09-14 13:46:12,537] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:46:15,197] [log.py:224] [log:log_response] [WARNING]- Not Found: /newsedit/1/
[2022-09-14 13:46:15,198] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /newsedit/1/ HTTP/1.1" 404 9968
[2022-09-14 13:47:09,981] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:47:11,074] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:47:18,057] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:47:19,165] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:47:23,718] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:47:24,884] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:47:31,687] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:47:32,837] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:48:07,213] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:48:08,380] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:48:14,087] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:48:15,224] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:48:18,683] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 13:48:19,645] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:48:25,896] [log.py:224] [log:log_response] [WARNING]- Not Found: /newsedit/2/
[2022-09-14 13:48:25,896] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /newsedit/2/ HTTP/1.1" 404 10140
[2022-09-14 13:48:29,320] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101965
[2022-09-14 13:48:29,511] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:48:31,789] [log.py:224] [log:log_response] [WARNING]- Not Found: /newsedit/3/
[2022-09-14 13:48:31,790] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /newsedit/3/ HTTP/1.1" 404 10140
[2022-09-14 13:48:39,850] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:48:43,208] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 13:50:11,991] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 13:50:13,282] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:51:05,900] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:51:05,903] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:51:06,502] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:51:06,503] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:51:07,101] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:51:07,102] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:51:07,407] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101965
[2022-09-14 13:51:07,540] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:51:09,591] [log.py:224] [log:log_response] [WARNING]- Not Found: /newsedit/3/
[2022-09-14 13:51:09,592] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /newsedit/3/ HTTP/1.1" 404 10140
[2022-09-14 13:51:12,884] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 724
[2022-09-14 13:51:12,943] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:51:15,572] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11439
[2022-09-14 13:51:15,621] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:51:20,918] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11439
[2022-09-14 13:51:20,966] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:53:31,824] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:53:50,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 13:53:55,406] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:53:55,407] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:53:56,012] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:53:56,013] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:53:56,631] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 13:53:56,631] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 13:53:56,976] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101965
[2022-09-14 13:53:57,050] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:53:58,346] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11439
[2022-09-14 13:53:58,377] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:55:17,125] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:55:21,001] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101965
[2022-09-14 13:55:21,161] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:55:23,043] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newsadd/ HTTP/1.1" 200 5624
[2022-09-14 13:55:23,075] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:55:27,595] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 639
[2022-09-14 13:55:27,636] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:56:34,148] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 705
[2022-09-14 13:56:34,188] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:57:59,853] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 740
[2022-09-14 13:57:59,887] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 13:59:30,430] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 13:59:32,786] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 14:00:07,187] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:00:07,188] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 14:00:07,800] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:00:07,800] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 14:00:08,208] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /homelist/ HTTP/1.1" 200 2559
[2022-09-14 14:00:08,289] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:00:08,349] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:00:12,587] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37738
[2022-09-14 14:00:12,630] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:00:14,267] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101983
[2022-09-14 14:00:14,422] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:44:55,322] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101983
[2022-09-14 14:44:55,496] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:44:58,209] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:44:58,210] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 14:44:58,806] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:44:58,806] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 14:44:59,419] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:44:59,420] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 14:44:59,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist HTTP/1.1" 301 0
[2022-09-14 14:44:59,771] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101983
[2022-09-14 14:44:59,851] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:45:02,059] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37738
[2022-09-14 14:45:02,091] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:45:18,677] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 741
[2022-09-14 14:45:18,723] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:45:39,552] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parkadd/ HTTP/1.1" 200 11457
[2022-09-14 14:45:39,593] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:46:11,647] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101983
[2022-09-14 14:46:11,706] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:46:11,810] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:46:13,411] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37738
[2022-09-14 14:46:13,449] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:46:14,772] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 101983
[2022-09-14 14:46:14,844] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:46:14,954] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:47:01,567] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 740
[2022-09-14 14:47:01,601] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 14:53:40,739] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 14:53:40,740] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 15:12:15,006] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:16,375] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:12:20,113] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:21,258] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:12:22,866] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:23,903] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:12:31,639] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:32,972] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:12:37,910] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:39,455] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:12:41,743] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:12:42,926] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:22:50,882] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:22:52,336] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:22:54,874] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:22:55,962] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:23:03,650] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:23:04,823] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:23:10,669] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:23:11,827] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:23:20,283] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:23:21,442] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:23:27,730] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:23:29,117] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:24:10,794] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:24:12,019] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:25:14,660] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:25:16,016] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:25:18,390] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:25:19,377] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:25:58,210] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:25:59,397] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:08,705] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:10,063] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:13,724] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:14,943] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:17,131] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:18,401] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:20,503] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:21,687] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:23,885] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:25,101] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:28,207] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:29,344] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:26:33,769] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
[2022-09-14 15:26:35,059] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:40:00,045] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 15:40:11,992] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 15:40:40,226] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 15:40:40,227] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 15:40:40,834] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 15:40:40,835] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 15:40:41,247] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /homelist/ HTTP/1.1" 200 2559
[2022-09-14 15:40:41,297] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:40:41,339] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:40:44,966] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 3359
[2022-09-14 15:40:45,000] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:40:46,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 741
[2022-09-14 15:40:46,755] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:42:11,547] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /addpark/ HTTP/1.1" 200 741
[2022-09-14 15:42:11,581] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:42:15,128] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addpark/ HTTP/1.1" 200 741
[2022-09-14 15:42:16,816] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37738
[2022-09-14 15:42:16,850] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:42:18,785] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 3256
[2022-09-14 15:42:18,818] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:42:19,827] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 740
[2022-09-14 15:42:19,875] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:42:27,650] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addnews/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 234, in add_news
    fatherParkID= NewsPosts.objects.get(id=row[8].value)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
polls.models.NewsPosts.DoesNotExist: NewsPosts matching query does not exist.
[2022-09-14 15:42:27,654] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addnews/ HTTP/1.1" 500 82138
[2022-09-14 15:43:57,133] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /newslist/ HTTP/1.1" 200 3256
[2022-09-14 15:43:57,175] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:43:58,391] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 740
[2022-09-14 15:43:58,439] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:44:08,540] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addnews/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 234, in add_news
    fatherParkID= NewsPosts.objects.get(id=row[8].value)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
polls.models.NewsPosts.DoesNotExist: NewsPosts matching query does not exist.
[2022-09-14 15:44:08,542] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addnews/ HTTP/1.1" 500 82140
[2022-09-14 15:48:34,042] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addnews/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 234, in add_news
    fatherParkID= NewsPosts.objects.get(id=row[8].value)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
polls.models.NewsPosts.DoesNotExist: NewsPosts matching query does not exist.
[2022-09-14 15:48:34,044] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addnews/ HTTP/1.1" 500 84393
[2022-09-14 15:48:46,976] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /addnews/ HTTP/1.1" 200 740
[2022-09-14 15:48:47,032] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 15:49:06,965] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /addnews/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 234, in add_news
    fatherParkID= NewsPosts.objects.get(id=row[8].value)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
polls.models.NewsPosts.DoesNotExist: NewsPosts matching query does not exist.
[2022-09-14 15:49:06,969] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /addnews/ HTTP/1.1" 500 84392
[2022-09-14 16:06:37,886] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:06:37,888] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 16:06:38,495] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:06:38,496] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 16:06:38,992] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 16:06:51,558] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:06:51,559] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10140
[2022-09-14 16:06:52,196] [log.py:224] [log:log_response] [WARNING]- Not Found: /admin/
[2022-09-14 16:06:52,198] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /admin/ HTTP/1.1" 404 10125
[2022-09-14 16:08:28,736] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 16:08:29,927] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 16:08:36,857] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:08:36,858] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10246
[2022-09-14 16:08:37,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /a/ HTTP/1.1" 200 10137
[2022-09-14 16:08:38,137] [views.py:40] [views:counter] [INFO]- response result: {"code": 0, "data": 0}
[2022-09-14 16:08:38,138] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /api/count HTTP/1.1" 200 22
[2022-09-14 16:39:08,896] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:39:08,897] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10246
[2022-09-14 16:39:09,177] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 16:39:13,339] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /pack/ HTTP/1.1" 200 350820
[2022-09-14 16:39:13,736] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[2022-09-14 16:39:20,918] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 16:39:20,919] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10246
[2022-09-14 16:39:21,298] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /pack/1 HTTP/1.1" 301 0
[2022-09-14 16:39:21,836] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /pack/1/ HTTP/1.1" 200 33147
[2022-09-14 16:39:30,522] [basehttp.py:161] [basehttp:log_message] [INFO]- "PUT /pack/1/ HTTP/1.1" 200 33048
[2022-09-14 17:13:23,983] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:13:25,239] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:13:31,212] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:13:32,357] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:13:55,557] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:13:56,619] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:13:58,918] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:13:59,880] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:08,537] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:14:09,610] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:19,971] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:21,142] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:24,564] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:25,579] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:30,900] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:32,102] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:37,939] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:39,028] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:42,328] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:43,355] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:45,325] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:46,264] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:14:56,074] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:14:57,224] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:15:04,194] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:15:05,325] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:15:15,248] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:15:15,248] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10399
[2022-09-14 17:15:15,844] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:15:15,845] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10399
[2022-09-14 17:15:16,168] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login HTTP/1.1" 301 0
[2022-09-14 17:15:16,176] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 478
[2022-09-14 17:17:25,262] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2942
[2022-09-14 17:17:25,297] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:17:25,341] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:25:49,296] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 17:25:50,378] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:36:52,496] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 17:37:03,181] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 17:37:12,045] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:37:12,047] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10293
[2022-09-14 17:37:12,638] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:37:12,638] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10293
[2022-09-14 17:37:13,253] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:37:13,254] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10293
[2022-09-14 17:37:13,722] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2960
[2022-09-14 17:37:13,773] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:37:13,814] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:37:17,174] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 200 2960
[2022-09-14 17:37:17,223] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:37:20,860] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /login/ HTTP/1.1" 200 2960
[2022-09-14 17:37:20,910] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:38:30,478] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2963
[2022-09-14 17:38:30,524] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:38:33,845] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /homelist/ HTTP/1.1" 200 2559
[2022-09-14 17:38:33,903] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:39:58,023] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37727
[2022-09-14 17:39:58,057] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:40:03,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /homelist/ HTTP/1.1" 200 2565
[2022-09-14 17:40:03,131] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:40:05,687] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2969
[2022-09-14 17:40:05,731] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:50:09,424] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:50:10,566] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:50:12,824] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:50:13,785] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:54:00,140] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:54:01,245] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:54:06,910] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:54:08,024] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:54:13,674] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:54:14,742] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:54:20,344] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:54:21,513] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:54:28,698] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:54:29,762] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:55:05,679] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 17:55:06,869] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:56:29,853] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:56:31,141] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:57:00,044] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:57:24,273] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:57:25,475] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:57:36,762] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:57:37,941] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:58:02,046] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:58:03,223] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:58:13,438] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 17:58:16,638] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:58:16,639] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10460
[2022-09-14 17:58:17,246] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:58:17,247] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10460
[2022-09-14 17:58:17,574] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/ HTTP/1.1" 200 2969
[2022-09-14 17:58:17,629] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:58:17,670] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 17:58:27,746] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:58:28,928] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:58:33,338] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 17:58:33,338] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 17:58:33,904] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /loginss/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'users/login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login_register.html
[2022-09-14 17:58:33,908] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /loginss/ HTTP/1.1" 500 86232
[2022-09-14 17:58:46,922] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:58:52,020] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /loginss/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'users/login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login_register.html
[2022-09-14 17:58:52,024] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /loginss/ HTTP/1.1" 500 86369
[2022-09-14 17:58:55,480] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /loginss/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'users/login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login_register.html
[2022-09-14 17:58:55,482] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /loginss/ HTTP/1.1" 500 86369
[2022-09-14 17:59:23,738] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:59:24,868] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:59:34,009] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:59:35,064] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:59:37,286] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:59:38,283] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 17:59:42,414] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 17:59:43,631] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:00:05,539] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:00:06,623] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:01:51,539] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 18:01:52,715] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:01:59,555] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:02:00,606] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:02:12,102] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:02:13,250] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:02:28,138] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:02:29,327] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:02:33,248] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:02:34,382] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:02:51,561] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:03:05,197] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:03:05,197] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:03:05,682] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'users/login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login_register.html
[2022-09-14 18:03:05,686] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 86103
[2022-09-14 18:03:09,021] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'users/login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: users/login_register.html
[2022-09-14 18:03:09,024] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 86371
[2022-09-14 18:04:06,220] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 18:04:07,347] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:04:31,647] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py changed, reloading.
[2022-09-14 18:04:32,836] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:04:57,878] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:04:57,884] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124392
[2022-09-14 18:05:55,953] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:05:55,960] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124438
[2022-09-14 18:06:17,643] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:06:22,449] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:06:22,458] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124438
[2022-09-14 18:06:39,386] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:06:39,391] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124471
[2022-09-14 18:06:42,415] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:06:42,420] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124471
[2022-09-14 18:07:11,347] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:11,353] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:15,808] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:15,813] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:21,058] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:07:22,221] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:22,227] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:23,354] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:23,357] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:24,575] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:24,579] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:25,491] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:07:25,494] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 124307
[2022-09-14 18:07:34,017] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
[2022-09-14 18:07:34,023] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 123416
[2022-09-14 18:07:38,696] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /default/ HTTP/1.1" 200 1435
[2022-09-14 18:08:58,657] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:08:58,658] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:08:59,272] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:08:59,272] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:08:59,881] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:08:59,881] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:00,482] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:00,483] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:01,086] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:01,086] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:01,698] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:01,699] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:02,299] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:02,300] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:02,899] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:02,900] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:03,516] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:03,517] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:09:04,117] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 18:09:04,117] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10462
[2022-09-14 18:14:00,590] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:14:06,367] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /default/ HTTP/1.1" 200 1435
[2022-09-14 18:14:12,672] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 297, in loginUser
    login(request, user)
TypeError: login() takes 1 positional argument but 2 were given
[2022-09-14 18:14:12,674] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /default/ HTTP/1.1" 500 72599
[2022-09-14 18:15:44,838] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /default/ HTTP/1.1" 200 1565
[2022-09-14 18:15:50,760] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 297, in loginUser
    login(request, user)
TypeError: login() takes 1 positional argument but 2 were given
[2022-09-14 18:15:50,762] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /default/ HTTP/1.1" 500 72599
[2022-09-14 18:18:24,168] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:18:35,463] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    return parser.libraries[name]
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1094, in load
    lib = find_library(parser, name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1039, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
[2022-09-14 18:18:35,470] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 141709
[2022-09-14 18:19:38,016] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    return parser.libraries[name]
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1094, in load
    lib = find_library(parser, name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1039, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
[2022-09-14 18:19:38,020] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 141390
[2022-09-14 18:19:39,622] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1037, in find_library
    return parser.libraries[name]
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1094, in load
    lib = find_library(parser, name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 1039, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
[2022-09-14 18:19:39,627] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 141390
[2022-09-14 18:20:25,572] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:20:29,692] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'reset_password' not found. 'reset_password' is not a valid view function or pattern name.
[2022-09-14 18:20:29,700] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 122776
[2022-09-14 18:20:57,083] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 18:21:02,542] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'admin_urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 54: 'admin_urls'. Did you forget to register or load this tag?
[2022-09-14 18:21:02,551] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 136954
[2022-09-14 18:21:06,681] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'admin_urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 54: 'admin_urls'. Did you forget to register or load this tag?
[2022-09-14 18:21:06,687] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 136954
[2022-09-14 18:21:08,168] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'admin_urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 54: 'admin_urls'. Did you forget to register or load this tag?
[2022-09-14 18:21:08,174] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 136954
[2022-09-14 18:21:09,888] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'admin_urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 54: 'admin_urls'. Did you forget to register or load this tag?
[2022-09-14 18:21:09,892] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 136954
[2022-09-14 18:21:10,889] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'admin_urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 304, in loginUser
    return render(request, 'login_register.html')
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 54: 'admin_urls'. Did you forget to register or load this tag?
[2022-09-14 18:21:10,894] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /default/ HTTP/1.1" 500 136954
[2022-09-14 18:25:36,718] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /default/ HTTP/1.1" 200 1321
[2022-09-14 18:25:42,668] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /default/
Traceback (most recent call last):
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\young\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\zl\git-django-qyzs\django_wx_qhzs\polls\views.py", line 297, in loginUser
    login(request, user)
TypeError: login() takes 1 positional argument but 2 were given
[2022-09-14 18:25:42,669] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /default/ HTTP/1.1" 500 72599
[2022-09-14 21:23:35,730] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 21:23:36,892] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:24:09,466] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 21:24:10,590] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:24:13,342] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 21:24:14,313] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:24:40,629] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\urls.py changed, reloading.
[2022-09-14 21:24:41,814] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:24:47,924] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 21:24:56,127] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:24:56,128] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:24:56,732] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:24:56,733] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:24:57,349] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:24:57,350] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:24:57,950] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:24:57,951] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:05,731] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:05,732] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:11,399] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 21:25:17,000] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:17,002] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:17,613] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:17,614] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:18,212] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:18,214] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:18,812] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:18,813] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:19,428] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:19,430] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:20,045] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:20,046] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:20,649] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:20,650] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:21,271] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:21,272] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:21,880] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:21,881] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:22,504] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:22,505] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:23,113] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:23,114] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:24,315] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:25:24,328] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2969
[2022-09-14 21:25:24,378] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:25:24,443] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:25:54,369] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:54,370] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:54,983] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:54,984] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:55,606] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:55,607] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:56,214] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:56,214] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:56,814] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:56,815] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:57,431] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:57,432] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:58,031] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:58,031] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:58,632] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:58,632] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:59,233] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:59,234] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:25:59,844] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:25:59,844] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:26:00,448] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:26:00,449] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:26:01,064] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:26:01,065] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10568
[2022-09-14 21:26:01,464] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin HTTP/1.1" 301 0
[2022-09-14 21:26:01,471] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:26:01,492] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2969
[2022-09-14 21:26:01,552] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:26:01,631] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:26:38,423] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /homelist/ HTTP/1.1" 200 2565
[2022-09-14 21:26:38,479] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:26:38,542] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:26:43,847] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /parklist/ HTTP/1.1" 200 37727
[2022-09-14 21:26:43,893] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:30:25,705] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 21:30:26,908] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:30:31,577] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 21:30:32,730] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:30:35,015] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\urls.py changed, reloading.
[2022-09-14 21:30:36,157] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 21:30:54,968] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:30:54,969] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:30:55,563] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:30:55,564] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:30:56,158] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /loginsys HTTP/1.1" 301 0
[2022-09-14 21:30:56,173] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /loginsys/ HTTP/1.1" 200 2969
[2022-09-14 21:30:56,241] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /static/js/jquery-3.6.0.min.js HTTP/1.1" 404 1825
[2022-09-14 21:31:03,241] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:03,242] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:03,847] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:03,848] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:04,448] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:04,449] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:05,066] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:05,067] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:05,275] [log.py:224] [log:log_response] [WARNING]- Not Found: /login
[2022-09-14 21:31:05,276] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /login HTTP/1.1" 404 10553
[2022-09-14 21:31:15,856] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:15,857] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:16,465] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:31:16,466] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:31:16,800] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:31:16,835] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2212
[2022-09-14 21:31:16,893] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[2022-09-14 21:31:16,894] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[2022-09-14 21:31:16,896] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/login.css HTTP/1.1" 200 939
[2022-09-14 21:31:16,896] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[2022-09-14 21:31:16,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2022-09-14 21:31:16,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[2022-09-14 21:31:17,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2022-09-14 21:31:17,073] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2022-09-14 21:31:28,520] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2022-09-14 21:31:28,906] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 2874
[2022-09-14 21:31:28,941] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[2022-09-14 21:31:28,983] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2022-09-14 21:31:28,983] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2022-09-14 21:31:29,066] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2022-09-14 21:31:36,380] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6055
[2022-09-14 21:31:40,019] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 2874
[2022-09-14 21:32:02,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/logout/ HTTP/1.1" 200 1514
[2022-09-14 21:32:09,263] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:32:09,301] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2212
[2022-09-14 21:32:13,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:32:14,025] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2212
[2022-09-14 21:32:24,972] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:32:24,974] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:32:25,569] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:32:25,570] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:32:26,171] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 21:32:26,172] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 21:32:26,307] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 21:32:26,335] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2212
[2022-09-14 22:08:02,977] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:08:08,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 22:08:18,715] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6021
[2022-09-14 22:08:26,106] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:26,106] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:26,703] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:26,704] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:27,304] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:27,305] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:27,921] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:27,927] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:28,529] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:28,530] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:29,139] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:08:29,140] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:08:29,567] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
[2022-09-14 22:08:29,581] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4028
[2022-09-14 22:08:29,634] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/login.css?_=2.1 HTTP/1.1" 200 500
[2022-09-14 22:08:29,635] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/css/all.min.css HTTP/1.1" 200 55111
[2022-09-14 22:08:29,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/index.css HTTP/1.1" 200 238628
[2022-09-14 22:08:29,673] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/login.js?_=3.3 HTTP/1.1" 200 669
[2022-09-14 22:08:29,676] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/vue.min.js?_=2022.7.29 HTTP/1.1" 200 93675
[2022-09-14 22:08:29,693] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/particles/app.js HTTP/1.1" 200 3728
[2022-09-14 22:08:29,695] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/index.js?_=2022.7.29 HTTP/1.1" 200 586253
[2022-09-14 22:08:29,702] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/particles/particles.js HTTP/1.1" 200 51264
[2022-09-14 22:08:29,704] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/logo.png HTTP/1.1" 200 115997
[2022-09-14 22:08:29,708] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/img/bg.svg HTTP/1.1" 200 9547
[2022-09-14 22:08:29,884] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 74256
[2022-09-14 22:08:39,013] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/fonts/element-icons.woff HTTP/1.1" 200 28200
[2022-09-14 22:08:43,677] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2022-09-14 22:08:44,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 17277
[2022-09-14 22:08:44,283] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.css?_=2.1 HTTP/1.1" 200 3861
[2022-09-14 22:08:44,283] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css?_=3.2 HTTP/1.1" 200 6608
[2022-09-14 22:08:44,332] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2022.7.29 HTTP/1.1" 200 6292
[2022-09-14 22:08:44,336] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2022.7.29 HTTP/1.1" 200 1186
[2022-09-14 22:08:44,339] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2022.7.29 HTTP/1.1" 200 1254
[2022-09-14 22:08:44,341] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2022.7.29 HTTP/1.1" 200 524
[2022-09-14 22:08:44,341] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2022.7.29 HTTP/1.1" 200 4274
[2022-09-14 22:08:44,342] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2022.7.29 HTTP/1.1" 200 811
[2022-09-14 22:08:44,347] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2022.7.29 HTTP/1.1" 200 1189
[2022-09-14 22:08:44,349] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2022.7.29 HTTP/1.1" 200 6329
[2022-09-14 22:08:44,353] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2022.7.29 HTTP/1.1" 200 21460
[2022-09-14 22:08:44,546] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-brands-400.woff2 HTTP/1.1" 200 74768
[2022-09-14 22:14:55,880] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:14:57,076] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:06,495] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:07,727] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:15,877] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:17,624] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:20,345] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:21,579] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:23,570] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:24,657] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:26,688] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:27,734] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:30,926] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:31,976] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:44,219] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:15:45,507] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:15:46,564] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13552
[2022-09-14 22:15:50,006] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/logout/ HTTP/1.1" 200 161
[2022-09-14 22:15:50,374] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4013
[2022-09-14 22:17:04,474] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 22:17:06,193] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:34:53,340] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:35:10,201] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4005
[2022-09-14 22:35:23,663] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 22:35:26,210] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:35:31,603] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 22:35:34,366] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:35:39,476] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 22:35:41,869] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:35:50,623] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 22:35:52,668] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:35:56,331] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 22:35:59,582] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:36:01,619] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4005
[2022-09-14 22:36:21,614] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/ HTTP/1.1" 302 0
[2022-09-14 22:36:22,140] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 15951
[2022-09-14 22:36:33,815] [log.py:224] [log:log_response] [WARNING]- Not Found: /admin/auth/user/
[2022-09-14 22:36:33,815] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /admin/auth/user/ HTTP/1.1" 404 12623
[2022-09-14 22:36:35,743] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/auth/group/ HTTP/1.1" 200 28449
[2022-09-14 22:36:35,760] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css?_=2.7 HTTP/1.1" 200 19513
[2022-09-14 22:36:35,765] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/base.css?_=2.7 HTTP/1.1" 200 4160
[2022-09-14 22:36:35,766] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/simpleui.css HTTP/1.1" 200 4270
[2022-09-14 22:36:35,774] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/language.js?_=2.1.2 HTTP/1.1" 200 189
[2022-09-14 22:36:35,775] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js HTTP/1.1" 200 524
[2022-09-14 22:36:35,776] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js HTTP/1.1" 200 1254
[2022-09-14 22:36:35,776] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 200 6874
[2022-09-14 22:36:35,776] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css?_=20180905 HTTP/1.1" 200 18545
[2022-09-14 22:36:35,779] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2.1.2 HTTP/1.1" 200 811
[2022-09-14 22:36:35,793] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[2022-09-14 22:36:35,796] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[2022-09-14 22:36:35,796] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
[2022-09-14 22:36:35,797] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2022-09-14 22:36:35,804] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[2022-09-14 22:36:35,807] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[2022-09-14 22:36:35,808] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[2022-09-14 22:36:35,818] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js HTTP/1.1" 200 6292
[2022-09-14 22:36:35,818] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js HTTP/1.1" 200 1186
[2022-09-14 22:36:35,819] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/axios.min.js HTTP/1.1" 200 14237
[2022-09-14 22:36:35,822] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89476
[2022-09-14 22:36:35,825] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2022-09-14 22:36:36,107] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 22:36:40,824] [log.py:224] [log:log_response] [WARNING]- Not Found: /admin/tasks/task/
[2022-09-14 22:36:40,825] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /admin/tasks/task/ HTTP/1.1" 404 12626
[2022-09-14 22:59:06,849] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 22:59:12,277] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 6055
[2022-09-14 22:59:27,458] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:27,459] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:28,048] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:28,049] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:28,650] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:28,651] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:29,271] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:29,272] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:29,881] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:29,882] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:30,481] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-09-14 22:59:30,482] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 10571
[2022-09-14 22:59:31,591] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16389
[2022-09-14 22:59:38,870] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/auth/group/ HTTP/1.1" 200 28800
[2022-09-14 22:59:39,238] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:03:46,234] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:03:47,585] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:03:51,213] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:03:52,171] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:03:56,452] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:03:57,581] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:03:59,855] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:01,012] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:02,804] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:03,889] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:05,647] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:06,574] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:10,736] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:11,873] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:13,899] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:14,858] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:19,008] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:20,202] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:26,555] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:04:28,045] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:04:34,438] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16683
[2022-09-14 23:04:35,137] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/auth/group/ HTTP/1.1" 200 28800
[2022-09-14 23:04:35,483] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:05:08,979] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:05:09,320] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:05:17,579] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/70/change/ HTTP/1.1" 200 24166
[2022-09-14 23:05:17,613] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
[2022-09-14 23:05:17,615] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2022-09-14 23:05:17,618] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[2022-09-14 23:05:17,651] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[2022-09-14 23:05:17,930] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:05:23,256] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:05:23,602] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:05:33,524] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/add/ HTTP/1.1" 200 22155
[2022-09-14 23:05:33,882] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:05:42,302] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:05:42,682] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:06:27,410] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:06:28,631] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:07:25,730] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:07:46,383] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:07:47,543] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:09:30,485] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:09:35,117] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16723
[2022-09-14 23:09:43,151] [log.py:224] [log:log_response] [WARNING]- Not Found: /admin/polls/park/
[2022-09-14 23:09:43,152] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /admin/polls/park/ HTTP/1.1" 404 12796
[2022-09-14 23:09:53,287] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:09:53,608] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:11:04,002] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:11:05,177] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:11:08,629] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:11:09,607] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:11:14,148] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16723
[2022-09-14 23:11:15,041] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:11:15,410] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:11:17,528] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16723
[2022-09-14 23:11:18,431] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:11:18,752] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:11:29,921] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:11:36,455] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 16948
[2022-09-14 23:11:37,288] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:11:37,580] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:11:47,227] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:11:47,526] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:12:52,940] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:12:53,290] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:13:45,050] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:13:46,293] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:13:55,725] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:13:56,983] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:14:10,887] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:14:15,041] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 17171
[2022-09-14 23:14:15,936] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:14:16,261] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:14:24,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:14:25,065] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:14:29,588] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:14:29,932] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:14:41,816] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/223/change/ HTTP/1.1" 200 14604
[2022-09-14 23:14:42,127] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:14:48,525] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:14:48,818] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:15:17,156] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:15:18,493] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:15:44,263] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:15:49,722] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 17675
[2022-09-14 23:16:13,245] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:16:13,614] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:16:13,974] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:16:14,338] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:16:17,122] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:16:17,484] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:16:20,209] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/homedata/ HTTP/1.1" 200 25134
[2022-09-14 23:16:20,530] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:17:46,102] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:17:47,413] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:17:52,087] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\admin.py changed, reloading.
[2022-09-14 23:17:53,308] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:18:34,383] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:18:38,450] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 18221
[2022-09-14 23:18:39,115] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/homedata/ HTTP/1.1" 200 25134
[2022-09-14 23:18:39,451] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:18:49,250] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:18:49,602] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:18:49,889] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:18:50,212] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:18:56,323] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:18:56,627] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:18:57,765] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/news/ HTTP/1.1" 200 63618
[2022-09-14 23:18:58,076] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:19:00,110] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/park/ HTTP/1.1" 200 51448
[2022-09-14 23:19:00,455] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:19:03,310] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/homedata/ HTTP/1.1" 200 25134
[2022-09-14 23:19:03,621] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:19:12,942] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/homedata/2/change/ HTTP/1.1" 200 12347
[2022-09-14 23:19:13,256] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:19:17,330] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/homedata/ HTTP/1.1" 200 25134
[2022-09-14 23:19:17,661] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:19:54,877] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/polls/newsposts/ HTTP/1.1" 200 25464
[2022-09-14 23:19:55,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2022-09-14 23:20:45,394] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 23:20:46,666] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:20:48,947] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 23:20:49,971] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-14 23:20:57,574] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\wxcloudrun\settings.py changed, reloading.
[2022-09-14 23:20:58,984] [autoreload.py:637] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-09-15 13:26:43,794] [autoreload.py:251] [autoreload:trigger_reload] [INFO]- E:\zl\git-django-qyzs\django_wx_qhzs\polls\models.py changed, reloading.
